version: "3.7"

volumes:
  appdata:

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flutter_app
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
      - appdata:/app/build/web

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - appdata:/usr/share/nginx/html


