version: "3.7"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flutter_app
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html

