name: publishpoint
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  firebase_core: ^2.11.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  url_launcher: ^6.1.10
  flutter_web_plugins:
    sdk: flutter
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Golos
      fonts:
        - asset: assets/fonts/GolosText-Regular.ttf
        - asset: assets/fonts/GolosText-Medium.ttf
          weight: 500
        - asset: assets/fonts/GolosText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GolosText-Bold.ttf
          weight: 700